
global.toolParts = [
  'pickaxe_head',
  'axe_head',
  'shovel_blade',
  'hoe_blade',
  'sword_blade',
]

global.armorItems = {
  'lead': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'zinc': {
    'helmet': 'create_sa:zinc_helmet',
    'chestplate': 'create_sa:zinc_chestplate',
    'leggings': 'create_sa:zinc_leggings',
    'boots': 'create_sa:zinc_boots',
  },
  'aluminum': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'brass': {
    'helmet': 'create_sa:brass_helmet',
    'chestplate': 'create_sa:brass_chestplate',
    'leggings': 'create_sa:brass_leggings',
    'boots': 'create_sa:brass_boots',
  },
  'electrum': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'silver': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'gold': {
    'helmet': 'minecraft:golden_helmet',
    'chestplate': 'minecraft:golden_chestplate',
    'leggings': 'minecraft:golden_leggings',
    'boots': 'minecraft:golden_boots',
  },
  'copper': {
    'helmet': 'create_sa:copper_helmet',
    'chestplate': 'create_sa:copper_chestplate',
    'leggings': 'create_sa:copper_leggings',
    'boots': 'create_sa:copper_boots',
  },
  'cast_iron': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'uranium': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'constantan': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'nickel': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'iron': {
    'helmet': 'minecraft:iron_helmet',
    'chestplate': 'minecraft:iron_chestplate',
    'leggings': 'minecraft:iron_leggings',
    'boots': 'minecraft:iron_boots',
  },
  'steel': {
    'helmet': 'tfmg:steel_helmet',
    'chestplate': 'tfmg:steel_chestplate',
    'leggings': 'tfmg:steel_leggings',
    'boots': 'tfmg:steel_boots',
  },
  'palladium': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'platinum': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'chromium': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'vanadium': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'rhodium': {
    'helmet': '',
    'chestplate': '',
    'leggings': '',
    'boots': '',
  },
  'tungsten': {
    'helmet': 'createloveandwar:tungsten_helmet',
    'chestplate': 'createloveandwar:tungsten_chestplate',
    'leggings': 'createloveandwar:tungsten_leggings',
    'boots': 'createloveandwar:tungsten_boots',
  },
}

global.toolItems = {
  'lead': {
    'pickaxe_head': 'tfmg:lead_pickaxe',
    'axe_head': 'tfmg:lead_axe',
    'shovel_blade': 'tfmg:lead_shovel',
    'sword_blade': 'tfmg:lead_sword',
    'hoe_blade': 'tfmg:lead_hoe',
  },
  'zinc': {
    'pickaxe_head': 'create_sa:zinc_pickaxe',
    'axe_head': 'create_sa:zinc_axe',
    'shovel_blade': 'create_sa:zinc_shovel',
    'sword_blade': 'create_sa:zinc_sword',
    'hoe_blade': 'create_sa:zinc_hoe',
  },
  'aluminum': {
    'pickaxe_head': 'tfmg:aluminum_pickaxe',
    'axe_head': 'tfmg:aluminum_axe',
    'shovel_blade': 'tfmg:aluminum_shovel',
    'sword_blade': 'tfmg:aluminum_sword',
    'hoe_blade': 'tfmg:aluminum_hoe',
  },
  'brass': {
    'pickaxe_head': 'create_sa:brass_pickaxe',
    'axe_head': 'create_sa:brass_axe',
    'shovel_blade': 'create_sa:brass_shovel',
    'sword_blade': 'create_sa:brass_sword',
    'hoe_blade': 'create_sa:brass_hoe',
  },
  'electrum': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'silver': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'gold': {
    'pickaxe_head': 'minecraft:golden_pickaxe',
    'axe_head': 'minecraft:golden_axe',
    'shovel_blade': 'minecraft:golden_shovel',
    'sword_blade': 'minecraft:golden_sword',
    'hoe_blade': 'minecraft:golden_hoe',
  },
  'copper': {
    'pickaxe_head': 'create_sa:copper_pickaxe',
    'axe_head': 'create_sa:copper_axe',
    'shovel_blade': 'create_sa:copper_shovel',
    'sword_blade': 'create_sa:copper_sword',
    'hoe_blade': 'create_sa:copper_hoe',
  },
  'cast_iron': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'uranium': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'constantan': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'nickel': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'iron': {
    'pickaxe_head': 'minecraft:iron_pickaxe',
    'axe_head': 'minecraft:iron_axe',
    'shovel_blade': 'minecraft:iron_shovel',
    'sword_blade': 'minecraft:iron_sword',
    'hoe_blade': 'minecraft:iron_hoe',
  },
  'steel': {
    'pickaxe_head': 'tfmg:steel_pickaxe',
    'axe_head': 'tfmg:steel_axe',
    'shovel_blade': 'tfmg:steel_shovel',
    'sword_blade': 'tfmg:steel_sword',
    'hoe_blade': 'tfmg:steel_hoe',
  },
  'palladium': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'platinum': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'chromium': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'vanadium': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'rhodium': {
    'pickaxe_head': '',
    'axe_head': '',
    'shovel_blade': '',
    'sword_blade': '',
    'hoe_blade': '',
  },
  'tungsten': {
    'pickaxe_head': 'createloveandwar:tungsten_pickaxe',
    'axe_head': 'createloveandwar:tungsten_axe',
    'shovel_blade': 'createloveandwar:tungsten_shovel',
    'sword_blade': 'createloveandwar:tungsten_sword',
    'hoe_blade': 'createloveandwar:tungsten_hoe',
  },
}

global.tConstructToolParts = {
  'pickaxe_head': 'pick_head',
  'axe_head': 'small_axe_head',
  'sword_blade': 'small_blade',
  'shovel_blade': '',
  'hoe_blade': '',
}

global.metalHasTConstructItems = {
  'lead': true,
  'zinc': false,
  'aluminum': false,
  'brass': true,
  'electrum': true,
  'silver': true,
  'gold': false,
  'copper': true,
  'cast_iron': false,
  'uranium': false,
  'constantan': true,
  'nickel': false,
  'iron': true,
  'steel': true,
  'palladium': false,
  'platinum': false,
  'chromium': false,
  'vanadium': false,
  'rhodium': false,
  'tungsten': false,
}