#If enabled will output to the debug.log when a structure is disabled.
"Enable Debug" = false
#This list defines the structures that should be disabled from generating.
"Disabled Structures" = ["create_structures_arise:pillagersteampunkairship", "tconstruct:sky_slime_island", "tconstruct:blood_island", "tconstruct:earth_slime_island", "tconstruct:end_slime_island"]

