global.ingotDictionary = {
  'tin': 'tinore:tin_ingot',
  'lead': 'immersiveengineering:ingot_lead',
  'zinc': 'create:zinc_ingot',
  'aluminum': 'immersiveengineering:ingot_aluminum',
  'brass': 'create:brass_ingot',
  'bronze': 'tcintegrations:bronze_ingot',
  'electrum': 'createaddition:electrum_ingot',
  'silver': 'immersiveengineering:ingot_silver',
  'gold': 'minecraft:gold_ingot',
  'copper': 'minecraft:copper_ingot',
  'cast_iron': 'tfmg:cast_iron_ingot',
  'uranium': 'immersiveengineering:ingot_uranium',
  'constantan': 'immersiveengineering:ingot_constantan',
  'nickel': 'immersiveengineering:ingot_nickel',
  'iron': 'minecraft:iron_ingot',
  'steel': 'immersiveengineering:ingot_steel',
  'palladium': '',
  'platinum': '',
  'chromium': '',
  'vanadium': 'vintageimprovements:vanadium_ingot',
  'rhodium': '',
  'tungsten': 'createmetallurgy:tungsten_ingot',
}


global.metalBlocks = {
  'tin': 'tinore:block_of_tin',
  'lead': 'immersiveengineering:storage_lead',
  'zinc': 'create:zinc_block',
  'aluminum': 'immersiveengineering:storage_aluminum',
  'brass': 'create:brass_block',
  'bronze': 'tcintegrations:bronze_block',
  'electrum': 'immersiveengineering:storage_electrum',
  'silver': 'immersiveengineering:storage_silver',
  'gold': 'minecraft:gold_block',
  'copper': 'minecraft:copper_block',
  'cast_iron': 'tfmg:cast_iron_block',
  'uranium': 'immersiveengineering:storage_uranium',
  'constantan': 'immersiveengineering:storage_constantan',
  'nickel': 'immersiveengineering:storage_nickel',
  'iron': 'minecraft:iron_block',
  'steel': 'immersiveengineering:storage_steel',
  'palladium': '',
  'platinum': '',
  'chromium': '',
  'vanadium': 'vintageimprovements:vanadium_block',
  'rhodium': '',
  'tungsten': 'createmetallurgy:tungsten_block',
}

global.metalRods = {
  'tin': 'vintageimprovements:tin_rod',
  'lead': 'vintageimprovements:lead_rod',
  'zinc': 'vintageimprovements:zinc_rod',
  'aluminum': 'immersiveengineering:stick_aluminum',
  'brass': 'createaddition:brass_rod',
  'bronze': 'vintageimprovements:bronze_rod',
  'electrum': 'createaddition:electrum_rod',
  'silver': 'vintageimprovements:silver_rod',
  'gold': 'createaddition:gold_rod',
  'copper': 'createaddition:copper_rod',
  'cast_iron': 'vintageimprovements:cast_iron_rod',
  'uranium': 'vintageimprovements:uranium_rod',
  'constantan': 'vintageimprovements:constantan_rod',
  'nickel': 'vintageimprovements:nickel_rod',
  'iron': 'immersiveengineering:stick_iron',
  'steel': 'immersiveengineering:stick_steel',
  'palladium': '',
  'platinum': '',
  'chromium': '',
  'vanadium': 'vintageimprovements:vanadium_rod',
  'rhodium': '',
  'tungsten': '',
}


global.metalPlates = {
  'tin': 'vintageimprovements:tin_sheet',
  'lead': 'immersiveengineering:plate_lead',
  'zinc': 'createdeco:zinc_sheet',
  'aluminum': 'immersiveengineering:plate_aluminum',
  'brass': 'create:brass_sheet',
  'bronze': 'vintageimprovements:bronze_sheet',
  'electrum': 'immersiveengineering:plate_electrum',
  'silver': 'immersiveengineering:plate_silver',
  'gold': 'create:golden_sheet',
  'copper': 'create:copper_sheet',
  'cast_iron': 'vintageimprovements:cast_iron_sheet',
  'uranium': 'immersiveengineering:plate_uranium',
  'constantan': 'immersiveengineering:plate_constantan',
  'nickel': 'immersiveengineering:plate_nickel',
  'iron': 'create:iron_sheet',
  'steel': 'immersiveengineering:plate_steel',
  'palladium': 'vintageimprovements:palladium_sheet',
  'platinum': 'vintageimprovements:platinum_sheet',
  'chromium': '',
  'vanadium': 'vintageimprovements:vanadium_sheet',
  'rhodium': 'vintageimprovements:rhodium_sheet',
  'tungsten': 'createmetallurgy:tungsten_sheet',
}
